name: decide
description: Simple place to consciously make decisions where two or more options are available.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^0.2.0
  built_value: ^7.0.0
  built_value_generator: ^7.0.0
  build_runner: ^1.7.2
  uuid: ^2.0.4
  localstorage: ^3.0.1+4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true